### PR TITLE
add: slope-field

### PR DESCRIPTION
**Pull request by mdibaiee**
I created an slope-field visualization tool using Haskell while studying Calculus 1B: Integration! Thought I would share it with others. :D

### CODE REVIEW

**Comment by ericdouglas** [comment]
@mdibaiee awesome stuff. Many thanks for your contribution! :smile:

**Comment by ericdouglas** [comment]
@mdibaiee I just remembered that now our PROJECTS file is [here](https://github.com/open-source-society/computer-science/blob/master/PROJECTS.md).

Would you mind to make another PR there?

**Comment by mdibaiee** [comment]
@ericdouglas Yep, sure! I will update the data-science README to point to this new file, too!

**Comment by mdibaiee** [comment]
@ericdouglas oh, it seems the file you are pointing to is for the computer-science path, and doesn't represent the courses in data-science path. I think we need to move this file to data-science, hmm? :D

**Comment by ericdouglas** [comment]
@mdibaiee yeah, I saw that you are doing the DS course, so it'll be the right place.

I will remove the PROJECTS file from this repository.

Thanks again :smile:

**Pull request merged**
